### ISSUE TITLE
createImage does not work with PDFs

### ISSUE THREAD

**Issue by bergur** [rkusa/pdfjs#62]
Hey there, hoping you could help me :)

`var myImage = pdf.createImage(fs.readFileSync(__dirname + '/mypdf.pdf'));
doc.image(myImage);`

Gives
> Cannot read property 'content' of undefined","stack":"TypeError: Cannot read property 'content' of undefined\n    at new module.exports (/node_modules/pdfjs/dist/pdfjs.js:2937:34

`var contents = img.info.page.get('Contents').object`

Gives 
> undefined

When using a jpg image everything works perfectly :)

**Comment by rkusa** [comment]
Hi, to embed PDFs as images, the PDFs are parsed, which is a very error-prone task. Could you provide such a failing PDF so that I can checkout where the parsing fails?

**Comment by bergur** [comment]
Thanks for the quick reply:

[kvittun.pdf](https://github.com/rkusa/pdfjs/files/760457/kvittun.pdf)

**Comment by rkusa** [comment]
Should be fixed on `master`. Thanks for reporting, makes the parser more robust :-)

**Comment by bergur** [comment]
Thank you again for your swift responses.
I'm most likely doing something wrong, i still get the same error?

**Comment by rkusa** [comment]
I haven't published the update, yet. So you have to do `npm install rkusa/pdfjs` to install the current master. Have you tried this?

**Comment by bergur** [comment]
I installed straight from the git repository and got no errors just a blank page.
Same result if I install from rkusa/pdfjs

**Comment by rkusa** [comment]
What does your whole code look like?

I've tested it with

```js
const pdf = require('./lib')
const fs = require('fs')

const doc = new pdf.Document({
  font: new pdf.TTFFont(fs.readFileSync('regular.ttf'))
})

var myImage = pdf.createImage(fs.readFileSync(__dirname + '/kvittun.pdf'));
doc.image(myImage)

fs.writeFile('test.pdf', doc.render().toString(), 'binary')
```

And got

![screen shot 2017-02-08 at 14 04 04](https://cloud.githubusercontent.com/assets/409021/22738392/958238e0-ee07-11e6-8bac-79d5f431936f.png)

**Comment by bergur** [comment]
Yeah same code expect I had express with

`res.set('Content-Disposition','attachment');
same thing
res.send(doc.render().toString())`

Got it working with:
`res.end(doc.render().toString(),'binary');`

Thank you again so much for all your help! :)

**Comment by rkusa** [comment]
You are welcome!

**Comment by bergur** [comment]
Did this change ever get published to npm?
I've tried 1.0.0-alpha.5 but got the old error back up: cannot read poperty content of undefined.

I tried to update to version 2.0.0-alpha.1 but just get an error when doing require('pdfjs')

**Comment by rkusa** [comment]
Good point. I've published `1.0.0-alpha.6`. `2.0.0-alpha.1` probably throws because it requires a Node version >= 7
